# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e28b2b02e49d4de98f4486bbba81f0a4fe393abec5a2151ff42796d3e72c102b5fb6b7b6ef6c4fc607bfba5e1486bd80ec441b9c49de6b55e4105021f6bda39

test:
  secret_key_base: de8795ea5a8b104b5fee988af38c1194552713704bdd5fb197ed03887a4da27613bbe77f70d6407eac87459a74ae6b15f0e06299b97a2fbd57d9eac3c68c169c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
